const properties = [
    {
        id: "80233d31-ca00-4648-b1fb-e66d7db063ff",
        name: "Casa de Campito en Santa Cruz",
        province: "Guanacaste",
        canton: "Santa Cruz",
        district: "Santa Cruz",
        coordinates: {
            type: "Point",
            coordinates: [10.239877, -85.593247],
        },
        squareMeters: "400m²",
        forRent: true,
        bedroomNum: 3,
        bathroomNum: 2,
        garage: 3,
        rentalPrice: 300,
        description: "Acogedora casa de campo con amplio jardín.",
        restrictions: "No se permiten mascotas.",
        photos: "https://i.ytimg.com/vi/LxZqUYNg2W4/maxresdefault.jpg",
        UserId: "80233d31-ca00-4648-b1fb-e66d7db063fe",
    },
    {
        id: "80233d31-ca00-4648-b1fb-e66d7db063fe",
        name: "Apartamento en el centro de Samara",
        province: "Guanacaste",
        canton: "Nicoya",
        district: "Sámara",
        coordinates: {
            type: "Point",
            coordinates: [9.883913, -85.525561],
        },
        squareMeters: "80m²",
        forRent: true,
        bedroomNum: 2,
        bathroomNum: 1,
        garage: 1,
        rentalPrice: 100,
        description: "Apartamento en el centro de la ciudad para dos personas o una familia de 3. Inluye cocina, sala, comedor, baño y dos habitaciones. está a 5 minutos de la playa y está cerca del supermercado y la farmacia.",
        restrictions: "No se permiten mascotas. No se permite fumar. No se permiten fiestas.",
        photos: "https://http2.mlstatic.com/D_NQ_NP_791846-MCR74390142864_022024-O.webp",
        UserId: "80233d31-ca00-4648-b1fb-e66d7db063fe",
    },
    {
        id: "80233d31-ca00-4648-b1fb-e66d7db063fd",
        name: "Casa de playa en Tamarindo",
        province: "Guanacaste",
        canton: "Santa Cruz",
        district: "Tamarindo",
        coordinates: {
            type: "Point",
            coordinates: [10.299167, -85.840000],
        },
        squareMeters: "100m²",
        forRent: false,
        bedroomNum: 4,
        bathroomNum: 3,
        garage: 2,
        salePrice: 949000,
        description: "Casa de playa con vista al mar. Incluye piscina y rancho. A 5 minutos de la playa. Ideal para familias grandes o grupos de amigos. Incluye cocina, sala, comedor, baño y cuatro habitaciones. Está cerca de supermercados, farmacias y restaurantes.",
        restrictions: "No se permiten mascotas.",
        photos: "https://media-cdn.tripadvisor.com/media/vr-splice-j/00/04/c0/5b.jpg",
        UserId: "80233d31-ca00-4648-b1fb-e66d7db063fe",
    }
];

export default properties;
